CREATE TYPE USER_STATUS AS  ENUM('ACTIVE', 'PASSIVE');
CREATE  TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    phone_number VARCHAR(100) NOT NULL UNIQUE,
    user_status USER_STATUS DEFAULT 'ACTIVE',
    password_hash VARCHAR(255) NOT NULL,
    last_login TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);