CREATE TYPE ADMIN_STATUS AS ENUM('ACTIVE', 'PASSIVE');
CREATE  TYPE ADMIN_ROLE AS ENUM('SUPER_ADMIN', 'ADMIN', 'MODERATOR', 'WRITER', 'EDITOR');
CREATE TABLE IF NOT EXISTS admins(
    id SERIAL PRIMARY KEY ,
    username VARCHAR(100) NOT NULL,
    phone_number VARCHAR(100) NOT NULL UNIQUE,
    user_status ADMIN_STATUS DEFAULT 'ACTIVE',
    admin_role ADMIN_ROLE DEFAULT 'MODERATOR',
    password_hash VARCHAR(255) NOT NULL,
    last_login TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);